services:
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: tododb
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
  # todo:
  #   image: todo:latest
  #   restart: unless-stopped
  #   environment:
  #     DB_USER: 'user'
  #     DB_PASSWORD: 'password'
  #     DB_HOST: 'db:3306'
  #     DB_NAME: 'todo'
  #     PORT: 8081
  #   ports:
  #     - '8081:8081'
  #   expose:
  #     - '8081'